# ===================================================================
# DEFAULT / LOCAL PROFILE  (for running on your machine)
# ===================================================================
server:
  port: 8080

spring:
  application:
    name: mantra-backend

  # --- Local MySQL Database ---
  datasource:
    url: jdbc:mysql://localhost:3306/mantra_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 699123s@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# ===================================================================
# PRODUCTION PROFILE (for Render deployment)
# ===================================================================
---
spring:
  config:
    activate:
      on-profile: production

  # --- PostgreSQL Database Configuration (Render) ---
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${SPRING_JPA_SHOW_SQL:false}
        format_sql: true

server:
  port: ${PORT:8080}

# ===================================================================
# JWT + Security
# ===================================================================
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

security:
  user:
    password: ${DEFAULT_ADMIN_PASSWORD}

# ===================================================================
# External Service Integrations
# ===================================================================
openrouter:
  api:
    key: ${OPENROUTER_API_KEY}

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
    secret: ${RAZORPAY_SECRET_KEY}

# ===================================================================
# Logging / Debug
# ===================================================================
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: INFO
