# This file is for LOCAL development only

server:
  port: 8080

spring:
  application:
    name: mantra-backend
  # --- Local MySQL Database ---
  datasource:
    url: jdbc:mysql://localhost:3306/mantra_db
    username: root
    password: your_local_password # Change if needed
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect