server:
  port: 8080

spring:
  application:
    name: mantra-backend

  datasource:
    url: jdbc:mysql://localhost:3306/mantra_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 699123s@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    user:
      password: admin

# JWT Configuration
jwt:
  secret: qn+w2iYtsaOZgVWeArJCIsmJVTRiJrvXfjPwlGI8SkVPe+tPY9wvim+u80EWLNMec+9IWu+wiBu3Qsujn8Reew==
  expiration: 86400000 # 24 hours

# OpenRouter API Configuration (DeepSeek R1 Distill Llama)
openrouter:
  api:
    key: ${OPENROUTER_API_KEY:}
    url: https://openrouter.ai/api/v1/chat/completions


# Logging
logging:
  level:
    com.mantra: DEBUG
    org.springframework.security: DEBUG

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html